---
title: "Informe_calidad_cuencas"
author: "Hebenor Bermudez CI: 2.796.603-1"
date: "2023-01-16"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(here)
library(readr)
library(knitr)
library(kableExtra)

```

```{r}

#Se cargan los datos a partir del archivo de google.
datos <- read_csv(here("datos_cuencas.csv"))
```

```{r}
#Se hace el cálculo de la medida 1 que se calcula como ele_corr/elementos.

m1 <- datos %>% 
  mutate(datos, m1 = signif(ele_corr/elementos, digits = 3)) %>% 
  summarise(m1_media = round(mean(m1), 3),
            m1_mediana = round(median(m1), 3),
            m1_max = round(max(m1), 3),
            m1_min = round(min(m1), 3))

kable(m1, booktabs = TRUE, col.names = c("Media","Mediana","Máximo", "Mínimo"))

require(knitr)
require(kableExtra)
m1 %>% 
  kable(booktabs = TRUE, 
        format = "latex") %>% 
  kable_styling(
    latex_options = c("striped", "condensed"),
    position = "center",
    full_width = FALSE
  )

```


## R Markdown

